package com.adjaba.news

object Utils {
    val countryRss: Map<String, String> = mapOf(
        // Global / major
        "United States" to "https://rss.cnn.com/rss/cnn_us.rss",
        "United Kingdom" to "https://feeds.bbci.co.uk/news/uk/rss.xml",
        "Canada" to "https://www.cbc.ca/cmlink/rss-canada",
        "Australia" to "https://www.abc.net.au/news/feed/51120/rss.xml",
        "International - Reuters" to "https://www.reuters.com/tools/rss",

        // Europe
        "Germany" to "https://rss.dw.com/rdf/rss-en-top",
        "France" to "https://www.france24.com/en/rss",
        "Spain" to "https://feeds.elpais.com/mrss-s/pages/ep/site/elpais.com/portada",
        "Italy" to "https://www.ansa.it/ansat/sito/notizie/cronaca/rss.xml",
        "Netherlands" to "https://www.nu.nl/international.rss",
        "Sweden" to "https://www.thelocal.se/feed/",
        "Switzerland" to "https://www.swissinfo.ch/eng/rss/news",
        "Norway" to "https://www.nrk.no/toppsaker.rss",
        "Poland" to "https://www.thenews.pl/rss.xml",
        "Greece" to "https://www.ekathimerini.com/feed/",

        // Middle East & North Africa
        "Egypt" to "https://english.ahram.org.eg/rss/News/1.aspx",
        "Saudi Arabia" to "https://www.arabnews.com/rss.xml",
        "United Arab Emirates" to "https://gulfnews.com/rss?format=xml",
        "Qatar" to "https://www.gulf-times.com/rss",
        "Jordan" to "https://jordantimes.com/rss.xml",
        "Lebanon" to "https://www.dailystar.com.lb/RSS",
        "Morocco" to "https://www.leconomiste.com/rss", // major francophone source
        "Tunisia" to "https://www.tuniscope.com/rss",

        // Africa (selected)
        "South Africa" to "https://www.news24.com/rss",
        "Kenya" to "https://www.nation.africa/rss/latest/3514-4388274-format-rss.xml",
        "Nigeria" to "https://www.premiumtimesng.com/feed",

        // Asia
        "India" to "https://timesofindia.indiatimes.com/rssfeedstopstories.cms",
        "Pakistan" to "https://www.dawn.com/feeds/home",
        "Bangladesh" to "https://www.thedailystar.net/rss.xml",
        "Sri Lanka" to "https://www.ft.lk/feeds/news",
        "China" to "https://www.globaltimes.cn/RSS/Top.xml", // international-facing feed
        "Japan" to "https://www3.nhk.or.jp/rss/news/cat0.xml",
        "South Korea" to "http://www.koreaherald.com/rss/home.php",
        "Indonesia" to "https://www.thejakartapost.com/feed/",
        "Malaysia" to "https://www.thestar.com.my/rss/FeedProcessor.ashx?ContentType=RSS",
        "Philippines" to "https://www.philstar.com/rss/top-stories",

        // Americas (selected)
        "Mexico" to "https://www.eluniversal.com.mx/rss/noticias.xml",
        "Brazil" to "https://g1.globo.com/dynamo/rss2.xml",
        "Argentina" to "https://www.clarin.com/rss",
        "Chile" to "https://www.emol.com/rss/portada.xml",
        "Peru" to "https://elcomercio.pe/rss/portada/",

        // Smaller / other (use leading national outlet)
        "Turkey" to "https://www.hurriyet.com.tr/rss",
        "Iran" to "https://en.irna.ir/rss",
        "Israel" to "https://www.timesofisrael.com/feed/",
        "UAE - Khaleej Times" to "https://www.khaleejtimes.com/feed",

        // Fallback placeholders (empty = no single canonical feed found)
        "Afghanistan" to "",
        "Albania" to "",
        "Algeria" to "",
        "Andorra" to "",
        "Angola" to "",
        "Armenia" to "",
        "Azerbaijan" to "",
        "Bahamas" to "",
        "Bahrain" to "",
        "Belarus" to "",
        "Belize" to "",
        "Benin" to "",
        "Bhutan" to "",
        "Bolivia" to "",
        "Bosnia and Herzegovina" to "",
        "Botswana" to "",
        "Brunei" to "",
        "Bulgaria" to "",
        "Burkina Faso" to "",
        "Burundi" to "",
        "Cambodia" to "",
        "Cameroon" to "",
        "Cape Verde" to "",
        "Central African Republic" to "",
        "Chad" to "",
        "Colombia" to "https://www.eltiempo.com/rss", // example
        "Costa Rica" to "",
        "Croatia" to "https://www.total-croatia-news.com/feed",
        "Cuba" to "https://cubadebate.cu/feed/",
        "Cyprus" to "",
        "Czech Republic" to "https://www.praguepost.com/rss",
        "Dominican Republic" to "",
        "Ecuador" to "",
        "El Salvador" to "",
        "Eritrea" to "",
        "Estonia" to "",
        "Ethiopia" to "",
        "Fiji" to "",
        "Finland" to "https://yle.fi/uutiset/rss/feed/uutiset.rss",
        "Gabon" to "",
        "Gambia" to "",
        "Georgia" to "",
        "Ghana" to "",
        "Grenada" to "",
        "Guatemala" to "",
        "Guinea" to "",
        "Guinea-Bissau" to "",
        "Guyana" to "",
        "Haiti" to "",
        "Honduras" to "",
        "Hungary" to "https://index.hu/rss",
        "Iceland" to "https://www.ruv.is/rss",
        "Iraq" to "https://www.rudaw.net/english/rss",
        "Ireland" to "https://www.rte.ie/news/rss",
        "Jamaica" to "",
        "Kazakhstan" to "",
        "Kyrgyzstan" to "",
        "Laos" to "",
        "Latvia" to "",
        "Lebanon" to "https://www.dailystar.com.lb/RSS",
        "Lithuania" to "",
        "Luxembourg" to "",
        "Madagascar" to "",
        "Malawi" to "",
        "Maldives" to "",
        "Mali" to "",
        "Malta" to "",
        "Marshall Islands" to "",
        "Mauritania" to "",
        "Mauritius" to "",
        "Micronesia" to "",
        "Moldova" to "",
        "Monaco" to "",
        "Mongolia" to "",
        "Montenegro" to "",
        "Mozambique" to "",
        "Myanmar" to "https://www.mmtimes.com/rss.xml",
        "Namibia" to "",
        "Nauru" to "",
        "Nepal" to "https://kathmandupost.com/feed",
        "Nicaragua" to "",
        "Niger" to "",
        "North Korea" to "", // limited public feeds
        "North Macedonia" to "",
        "Oman" to "https://timesofoman.com/rss",
        "Palau" to "",
        "Panama" to "",
        "Papua New Guinea" to "",
        "Paraguay" to "",
        "Philippines" to "https://www.philstar.com/rss/top-stories",
        "Portugal" to "https://www.publico.pt/rss",
        "Romania" to "https://www.romania-insider.com/rss",
        "Russia" to "https://www.rt.com/rss", // note: editorial standpoint varies
        "Rwanda" to "",
        "Samoa" to "",
        "San Marino" to "",
        "Seychelles" to "",
        "Sierra Leone" to "",
        "Singapore" to "https://www.straitstimes.com/news/world/rss.xml",
        "Slovakia" to "",
        "Slovenia" to "",
        "Solomon Islands" to "",
        "Somalia" to "",
        "South Sudan" to "",
        "Suriname" to "",
        "Swaziland (Eswatini)" to "",
        "Syria" to "",
        "Taiwan" to "https://www.taipeitimes.com/News/rss",
        "Tajikistan" to "",
        "Tanzania" to "",
        "Togo" to "",
        "Tonga" to "",
        "Tunisia" to "https://www.tuniscope.com/rss",
        "Turkmenistan" to "",
        "Tuvalu" to "",
        "Uganda" to "",
        "Ukraine" to "https://www.pravda.com.ua/rss/",
        "Uruguay" to "",
        "Uzbekistan" to "",
        "Vanuatu" to "",
        "Vatican City" to "https://www.vaticannews.va/content/vaticannews/en.html.feed",
        "Venezuela" to "",
        "Vietnam" to "https://vietnamnews.vn/rss",
        "Yemen" to "",
        "Zambia" to "",
        "Zimbabwe" to ""
    )
     var NewsList: MutableList<RssItem> =mutableListOf()
}